language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - "pip install cython"
  - "pip install -r requirements/common.txt"
script: nosetests
notifications:
  email:
    - oscar.carballal@clione.io
